export enum PermissionEnum {
    READ_OWN_REDIRECTION = `READ_OWN_REDIRECTION`,
    READ_OTHER_REDIRECTION = `READ_OTHER_REDIRECTION`,

    MANAGE_OWN_BASIC_REDIRECTION = `MANAGE_OWN_BASIC_REDIRECTION`,
    MANAGE_OWN_PREMIUM_REDIRECTION = `MANAGE_OWN_PREMIUM_REDIRECTION`,

    MANAGE_USERS = `MANAGE_USERS`,
    MANAGE_ROLES = `MANAGE_ROLES`,
    MANAGE_PERMISSIONS = `MANAGE_PERMISSIONS`,
    MANAGE_OTHER_REDIRECTIONS = `MANAGE_OTHER_REDIRECTIONS`,
    MANAGE_OTHER_BASIC_REDIRECTIONS = `MANAGE_OTHER_BASIC_REDIRECTIONS`,
    MANAGE_OTHER_PREMIUM_REDIRECTIONS = `MANAGE_OTHER_PREMIUM_REDIRECTIONS`,
}
