x-app-backend-base: &app-backend-base
  container_name: short-links-manager-backend
  restart: always
  environment:
    SECRET: ${SECRET}
    NODE_ENV: ${NODE_ENV}
    MAIN_DATABASE_HOST: ${MAIN_DATABASE_HOST}
    MAIN_DATABASE_PORT: ${MAIN_DATABASE_PORT}
    MAIN_DATABASE_USER: ${MAIN_DATABASE_USER}
    MAIN_DATABASE_PASS: ${MAIN_DATABASE_PASS}
    MAIN_DATABASE_NAME: ${MAIN_DATABASE_NAME}
  networks:
    - short-links-manager-network

services:
  short-links-manager-backend-dev:
    <<: *app-backend-base
    image: short-links-manager-backend-dev
    build:
      context: ../
      target: development
      dockerfile: ./docker/Dockerfile.backend
    tty: true
    volumes:
      - ../backend:/usr/src/app
    profiles: [dev, backend-dev]
    depends_on:
      - short-links-manager-database-dev
    ports:
      - "127.0.0.1:5000:3000"
    expose:
      - 5000
    command: npm run start:dev

  short-links-manager-backend-prod:
    <<: *app-backend-base
    image: short-links-manager-backend-prod
    build:
      context: ../
      target: production
      dockerfile: ./docker/Dockerfile.backend
    profiles: [prod, backend-prod]
    depends_on:
      - short-links-manager-database-prod
    command: npm run start:prod
