x-app-backend-base: &app-backend-base
  container_name: short-links-manager-backend
  restart: always
  environment:
    SECRET: ${SECRET}
    NODE_ENV: ${NODE_ENV}
    ORIGIN: ${ORIGIN}
    MAIN_DATABASE_HOST: ${MAIN_DATABASE_HOST}
    MAIN_DATABASE_PORT: ${MAIN_DATABASE_PORT}
    MAIN_DATABASE_USER: ${MAIN_DATABASE_USER}
    MAIN_DATABASE_PASS: ${MAIN_DATABASE_PASS}
    MAIN_DATABASE_NAME: ${MAIN_DATABASE_NAME}
    SMTP_PASS: ${SMTP_PASS}
    SMTP_HOST: ${SMTP_HOST}
    SMTP_PORT: ${SMTP_PORT}
    SMTP_USER: ${SMTP_USER}
    SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
    MINIO_ENDPOINT: ${MINIO_ENDPOINT}
    MINIO_PORT: ${MINIO_PORT}
    MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    REDIS_HOST: ${REDIS_HOST}
    REDIS_PORT: ${REDIS_PORT}
    REDIS_PASSWORD: ${REDIS_PASSWORD}
  networks:
    - short-links-manager-network

services:
  short-links-manager-backend-dev:
    <<: *app-backend-base
    image: short-links-manager-backend-dev
    build:
      context: ../
      target: development
      dockerfile: ./docker/Dockerfile.backend
    tty: true
    volumes:
      - ../backend:/usr/src/app
    profiles: [ dev, backend-dev ]
    depends_on:
      - short-links-manager-database-dev
      - short-links-manager-redis-dev
      - short-links-manager-minio-dev
    ports:
      - "127.0.0.1:5000:3000"
    expose:
      - 5000
    command: npm run start:dev

  short-links-manager-backend-prod:
    <<: *app-backend-base
    image: short-links-manager-backend-prod
    build:
      context: ../
      target: production
      dockerfile: ./docker/Dockerfile.backend
    profiles: [ prod, backend-prod ]
    depends_on:
      - short-links-manager-database-prod
      - short-links-manager-redis-prod
      - short-links-manager-minio-prod
    command: npm run start:prod
