name: short-links-manager

include:
  - app-adminer-compose.yml
  - app-backend-compose.yml
  - app-frontend-compose.yml
  - app-router-compose.yml
  - app-minio-compose.yml
  - app-database-compose.yml

volumes:
  main-database-volume:
  caddy-config:
  minio-data:
  minio-config:
  caddy-logs:

networks:
  short-links-manager-network: