name: short-links-manager

include:
  - app-adminer-compose.yml
  - app-backend-compose.yml
  - app-frontend-compose.yml
  - app-router-compose.yml
  - app-database-compose.yml

volumes:
  main-database-volume:
  caddy_config:

networks:
  short-links-manager-network: