export enum CodeActionEnum {
    RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST",
    RESET_PASSWORD_CONFIRM = "RESET_PASSWORD_CONFIRM",
    VERIFY_EMAIL = "VERIFY_EMAIL",
    DELETE_ACCOUNT_CONFIRM = "DELETE_ACCOUNT_CONFIRM",
}
