export enum EmailerEventsEnum {
    REGISTRATION_CODE = "REGISTRATION_CODE",
    PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST",
    PASSWORD_RESET_CONFIRM = "PASSWORD_RESET_CONFIRM",
    ACCOUNT_DELETION = "ACCOUNT_DELETION",
}